package thirdeye.thirdeye;

import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;
import com.google.gson.Gson;
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.RequestBody;


import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Locale;

import com.squareup.okhttp.RequestBody;

import android.app.Activity;
import android.app.AlarmManager;
import android.app.PendingIntent;
import android.content.Context;
import android.content.Intent;
import android.hardware.Camera;
import android.media.AudioManager;
import android.os.AsyncTask;
import android.os.Bundle;
import android.os.Environment;
import android.provider.MediaStore;
import android.provider.Settings;
import android.speech.tts.TextToSpeech;
import android.util.Log;
import android.view.KeyEvent;
import android.view.SurfaceHolder;
import android.view.SurfaceView;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.TextView;

import org.json.JSONException;
import org.json.JSONObject;


/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity implements TextToSpeech.OnInitListener,Camera.ShutterCallback,Camera.PictureCallback,SurfaceHolder.Callback{

    /** {@link CardScrollView} to use as the main content view. */
    private CardScrollView mCardScroller;
    private SurfaceView mSurfaceView;
    private Camera cam;
    /** "Hello World!" {@link View} generated by {@link #buildView()}. */
    private View mView;

    private TextToSpeech mTts;
    private int  MY_DATA_CHECK_CODE =123;

    @Override
    protected void onActivityResult(
            int requestCode, int resultCode, Intent data) {
        Log.i(TAG,"onActivityResult"+resultCode);
        if (requestCode == MY_DATA_CHECK_CODE) {
            if (resultCode == TextToSpeech.Engine.CHECK_VOICE_DATA_PASS) {
                // success, create the TTS instance
                mTts = new TextToSpeech(this, this);
            } else {
                // missing data, install it
                Intent installIntent = new Intent();
                installIntent.setAction(
                        TextToSpeech.Engine.ACTION_INSTALL_TTS_DATA);
                startActivity(installIntent);
            }
        }
    }

    private static final String TAG = "MyActivity";


    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        //mView = buildView();

        /* All the camera interaction is here */

        Settings.System.putInt(getContentResolver(), Settings.System.SCREEN_OFF_TIMEOUT, 600000);

        setContentView(R.layout.surface);
        mSurfaceView = (SurfaceView) findViewById(R.id.surf);

        cam = Camera.open();
        snapPicture();

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });

        Intent checkIntent = new Intent();
        checkIntent.setAction(TextToSpeech.Engine.ACTION_CHECK_TTS_DATA);
        startActivityForResult(checkIntent, MY_DATA_CHECK_CODE);
    }

//    public boolean onKeyDown(int keyCode, KeyEvent event) {
//        if (keyCode == KeyEvent.KEYCODE_DPAD_CENTER) {
//            // Stop the preview and release the camera.
//            // Execute your logic as quickly as possible
//            // so the capture happens quickly.
//            takePic();
//            try {
//                Thread.sleep(1000);
//            } catch (InterruptedException e) {
//                e.printStackTrace();
//            }
//
//            return false;
//        } else {
//            return super.onKeyDown(keyCode, event);
//        }
//    }

    @Override
    public void onShutter() {
        /* This is where we put shutter sound */
        return;
    }

    @Override
    public void onPictureTaken(byte[] bytes, Camera camera) {
        /* Callback interface used to supply image data from a photo capture. */
        FileOutputStream fos= null;

        /* Write byte array to jpeg file */
        try {
            File photo=new File(this.getCacheDir(), "3eyeout.jpg");
            if (photo.exists()) {
                photo.delete();
            }
            fos = new FileOutputStream(photo.getPath());
            fos.write(bytes);
            fos.close();
            Log.i("MainActivity", "the length of the file is:"+bytes.length);
            PhotoAsyncTask task = new PhotoAsyncTask();
            task.execute(photo.getPath());
        }
        catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        catch (IOException e){
            e.printStackTrace();
        }
        return;
    }

    @Override
    public void surfaceCreated(SurfaceHolder surfaceHolder) {
    }

    @Override
    public void surfaceChanged(SurfaceHolder surfaceHolder, int i, int i2, int i3) {
        Log.i("MainActivity", "surfaceHolder: " + surfaceHolder);
        Log.i("MainActivity", "cam: " + cam);
        if(surfaceHolder.getSurface() == null || cam == null) {
            return;
        }

        //stop preview before make changes
        cam.stopPreview();

        //start preview with new setting
        try {
            cam.setPreviewDisplay(surfaceHolder);
            cam.startPreview();
            cam.takePicture(this,null,null,this);
        } catch (IOException e) {
            Log.e("MainActivity","problem setting up camera",e);
        }
    }

    @Override
    public void surfaceDestroyed(SurfaceHolder surfaceHolder) {
        surfaceHolder.removeCallback(this);
        cam.lock();
        cam.stopPreview();
        cam.release();
        surfaceHolder = null;
    }

    private class PhotoAsyncTask extends AsyncTask<String, Void, JSONObject>{
        @Override
        protected JSONObject doInBackground(String... strings) {
            try {
                HttpResponse<JsonNode> response1 = Unirest.post("https://camfind.p.mashape.com/image_requests")
                        .header("X-Mashape-Key", "ShUTf8SqtjmshKYbArXXl2gL320Dp1cR03VjsnQpi8obslPzd1")
                        .field("image_request[language]", "en")
                        .field("image_request[locale]", "en_US")
                        .field("image_request[image]", new File(strings[0]))
                        .asJson();
                String token = response1.getBody().getObject().getString("token");
                String url = "https://camfind.p.mashape.com/image_responses/"+token;
                Log.i("MainActivity", "URL: " + url);
                String status = "not completed";
                HttpResponse<JsonNode> response2 = null;
                int count = 0;
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        findViewById(R.id.progressContainer).setVisibility(View.VISIBLE);
                    }
                });
                while(status.equals("not completed")) {
                    if(count == 20){
                        mTts.speak("This image was not recognized", TextToSpeech.QUEUE_FLUSH, null);
                        break;
                    }

                    long millis = System.currentTimeMillis();
                    if(count % 3 == 0){
                        mTts.speak("Processing", TextToSpeech.QUEUE_FLUSH, null);
                    }
                    response2 = Unirest.get(url)
                            .header("X-Mashape-Key", "K85lAwEbdKmshufNqOICGm668Apcp1WeRfsjsn7SnoMNGsd9qU")
                            .asJson();
                    status = response2.getBody().getObject().getString("status");
                    Log.i("MainActivity", "JSONBody: " + response2.getBody());


                    Thread.sleep(1000 - millis % 1000);
                    count++;
                }
                return response2.getBody().getObject();
            } catch (UnirestException e) {
                e.printStackTrace();
                return null;
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
                return null;
            }
            /* This should be JSONException and seriously I hate this but Android Studio made me do it :( */
            catch (Exception e) {
                e.printStackTrace();
                return null;
            }
        }
        @Override
        protected void onPostExecute(final JSONObject jsonObject) {
            super.onPostExecute(jsonObject);
            try {
                final String textToSpeak = jsonObject.get("name").toString();
                mTts.speak(textToSpeak, TextToSpeech.QUEUE_FLUSH, null);
                Log.i("MainActivity","should have read "+textToSpeak);
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        findViewById(R.id.progressbar).setVisibility(View.INVISIBLE);
                        ((TextView) findViewById(R.id.textview)).setText(textToSpeak);

                    }
                });
            } catch (JSONException e) {
                e.printStackTrace();
            } catch (NullPointerException e){
                mTts.speak("Internet not working. Please check your connection and try again.", TextToSpeech.QUEUE_FLUSH, null);
                e.printStackTrace();
            }
        }
    }

    /* Camera stuff */

    protected void snapPicture() {
        Log.i("MainActivity", "" + Camera.getNumberOfCameras());
        Log.i("MainActivity", "New debug");
        Log.i("MainActivity", "Camera params: " + cam.getParameters().toString());

        SurfaceHolder holder = mSurfaceView.getHolder();
        holder.addCallback(this);

        Log.i("MainActivity", "Surface holder done");
        Log.i("MainActivity", "Set preview display done");
        Log.i("MainActivity", "Start preview done");

        mCardScroller = new CardScrollView(this);
        mCardScroller.setAdapter(new CardScrollAdapter() {
            @Override
            public int getCount() {
                return 1;
            }

            @Override
            public Object getItem(int position) {
                return mView;
            }

            @Override
            public View getView(int position, View convertView, ViewGroup parent) {
                return mView;
            }

            @Override
            public int getPosition(Object item) {
                if (mView.equals(item)) {
                    return 0;
                }
                return AdapterView.INVALID_POSITION;
            }
        });

        Intent checkIntent = new Intent();
        checkIntent.setAction(TextToSpeech.Engine.ACTION_CHECK_TTS_DATA);
        startActivityForResult(checkIntent, MY_DATA_CHECK_CODE);

    }

    //////////////////////////////

    @Override
    protected void onResume() {
        super.onResume();
//        if (mCardScroller==null)
//        {
//            mCardScroller = new CardScrollView(this);
//        }
//        mCardScroller.activate();
        findViewById(R.id.progressContainer).setVisibility(View.GONE);
        ((TextView) findViewById(R.id.textview)).setText(getString(R.string.loading));

    }

    @Override
    protected void onPause() {
//        mCardScroller.deactivate();
        super.onPause();

    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

        card.setText(R.string.hello_world);
        return card.getView();
    }

    @Override
    public void onInit(int i) {
        Log.i("MainActivity", "Works: " + i);
        mTts.setLanguage(Locale.US);
    }

    @Override
    protected void onDestroy()
    {
        super.onDestroy();
        if ( mTts != null)
        {
            mTts.stop();
            mTts.shutdown();
        }
    }
}
